### ISSUE TITLE
Feature request: get MathJax to update along with Next.js' fast refresh

### ISSUE THREAD

**Issue by nguyenvukhang** [fast-reflexes/better-react-mathjax#10]
Next.js has a [fast-refresh](https://nextjs.org/docs/basic-features/fast-refresh) feature which enables real-time previewing of a website while editing source.

I'm using [MDX](https://mdxjs.com/docs/getting-started/#nextjs) inside of [Next.js](https://nextjs.org/docs/advanced-features/using-mdx) and while the markdown side of things fast-refresh just fine, the MathJax components require a reload to update.

**Comment by fast-reflexes** [comment]
This is an interesting topic! Will look into it when I have time and will also accept PRs of course :) Thanks for posting!

**Comment by nguyenvukhang** [comment]
Apparently this already works! I just needed to set the `dynamic` property for each `MathJax` component to true.

**Comment by fast-reflexes** [comment]
Nice!!! Yeah it makes sense indeed ... guess I could introduce some flag that detects whether we are in production or dev and if dev, always set the dynamic flag internally (so that users won't have to use the dynamic flag explicitly when they don't need it in production).

Thanks for getting back to me on this :)

I will leave it open as a reminder to document and look into this if it's ok with you? :)
