### ISSUE TITLE
It's not displaying some equations 

### ISSUE THREAD

**Issue by demonhunter3333** [fast-reflexes/better-react-mathjax#11]
I got a weird error. MathJax is showing

$$
S_n=\frac{n(a_1+a_n)}{2}
$$

... correctly, but not:

$$
S_{100}=\frac{100(a_1+a_{100})}{2}
$$

**Comment by fast-reflexes** [comment]
Seems to be working fine: https://codesandbox.io/s/user-example-9-gbsxe

<img width="183" alt="Screenshot 2022-02-04 at 08 00 03" src="https://user-images.githubusercontent.com/2438128/152485978-f8e282f7-227b-4eb0-b29d-c57ec73c2634.png">

Or what is the problem you mean? Did you perhaps add it as a string and forgot to put double `\\` in front of the `frac` instead of a single?

**Comment by demonhunter3333** [comment]
> 

Thanks for the quick reply!

I don't know how to do this in your CodeSandbox page, but are you able to show the whole Markdown content below though:

```
Arithmetic sequences have the common difference *d*, i.e., the difference
between adjacent terms is always the same. The expression for the nth term of
an arithmetic sequence is

$$
a_n = a_1 + (n –1)d
$$

The sum of n consecutive terms of an arithmetic sequence is

$$
S_n=\frac{n(a_1+a_n)}{2}
$$

where $a_1$ is the first term to be summed, *an* is the last term to be summed, and *n*
is the number of terms to be summed.. For example, consider the sequence: 3,11,19, ..... The sum of the first 100 terms of the sequence would be:


$$
S_{100}=\\frac{100(a_1+a_{100})}{2}
$$

From $a_{100}= 3 + (100 –1) 8 = 795$ we get


$$
S_{100}=\frac{100(a_1+a_{100})}{2}=\frac{100(3+795)}{2}=39,900
$$

```

Thank you!

**Comment by demonhunter3333** [comment]
I think my Markdown plugin is messing with the math.

Thank you!
