### ISSUE TITLE
Red part in NextJs but not in Storybook

### ISSUE THREAD

**Issue by JoaoPauloCMarra** [fast-reflexes/better-react-mathjax#14]
Implementing a basic usage of the library on both Storybook and NextJs application I get different results:

Nextjs
<img width="176" alt="Screenshot 2022-04-28 at 21 26 15" src="https://user-images.githubusercontent.com/976151/165868170-eb428521-1515-4ee5-9649-2f5e49074d31.png">

Storybook
<img width="157" alt="Screenshot 2022-04-28 at 21 26 18" src="https://user-images.githubusercontent.com/976151/165868174-40a4ed67-c432-4710-b5ad-e31be73dc2b6.png">

Formula used: 
'\\(\\ce{C3H5O(COOH)3}\\)'
<img width="150" alt="Screenshot 2022-04-28 at 21 28 17" src="https://user-images.githubusercontent.com/976151/165868221-0a179dfe-3994-4419-a083-179db332fd5c.png">

any idea why?

**Comment by fast-reflexes** [comment]
Are you using MathJax 2 in NextJs and MathJax 3 in Storybook?

Seems like there is a bug in MathJax 2 that gives the results you describe:

https://codesandbox.io/s/expressions-mj2-fail-53eq8y

But with MathJax 3 it works as it should:

https://codesandbox.io/s/expressions-mj3-success-i8yjtg

Since MathJax 2 is probably no longer maintained in terms of bug fixes, I don't know if there is any point filing a bug report with [them](https://github.com/mathjax/MathJax/issues) but perhaps it could result in something :)

Let me know if this solves your problem :)

**Comment by JoaoPauloCMarra** [comment]
Not sure this is the issue:

<img width="508" alt="Screenshot 2022-04-29 at 09 08 42" src="https://user-images.githubusercontent.com/976151/165941507-77f200fc-ae62-4314-95e7-52d4d6788340.png">
(in nextjs)

**Comment by JoaoPauloCMarra** [comment]
Kinda found a workaround...I had to add a formula in the first render of the page, as the actual formula is only shown on a few steps of the page forward, it renders with the red parts...but If I first render something in the first render It works as expected...

**Comment by fast-reflexes** [comment]
hmm.. this sounds very odd... could you replicate this in a code sandbox? I see no reason why it shouldn't work as intended even if there is no math on the first render. 

Like here: https://codesandbox.io/s/user-example-12-elltp7
