### ISSUE TITLE
Not rendering latex consistently

### ISSUE THREAD

**Issue by ben-brooker** [fast-reflexes/better-react-mathjax#18]
<img width="469" alt="Screenshot 2022-06-28 at 12 38 55" src="https://user-images.githubusercontent.com/107868502/176169959-92b9a03f-8e3a-453e-8be5-89a59a8e1b7e.png">

I am building a NextJS application with server-side rendering. This code works fine in some cases and not in others. For example, Upon refreshing a successfully rendered page, the wrapper seems to no longer work. Also, it seems to work well on edge but not safari. Are you aware of this issue? Is there a way around it? Thanks.

**Comment by fast-reflexes** [comment]
Can you recreate the behaviour in a sandbox perhaps?

**Comment by fast-reflexes** [comment]
It sounds like you have a complex setup with potentially some very particular scenarios...

* Flickering should be handled by `hideUntilTypeset` property.. there are also other tips and tricks regarding this if you read the docs here in Github.
* If there are dynamic updates to the content, you should set `dynamic` flag on the `MathJax` component.
* What do you mean by refreshing the page, a full page reload? If so, it seems there's something very particular at play 
  because it has never happened to me... Is there any errors in the console? If SOME page loads work and others don't, there 
  is some randomness, like the order of rendering or something, that causes problems.
* I assume the children are only text and HTML elements ... If there is other code running inside this child it may interact with 
  MathJax in a bad way since MathJax also manipulates the DOM. Try to switch the current content for something hard- 
  coded and see if the behaviour persists. If it does not, then there is something with this component that is problematic.

Can you point me to anywhere where this can be seen? Almost impossible to help out otherwise :(

**Comment by fast-reflexes** [comment]
Removing since no further information was added. Please reopen with more information if needed.
