### ISSUE TITLE
How to get a new line? 

### ISSUE THREAD

**Issue by nioclass** [fast-reflexes/better-react-mathjax#34]
I am trying to write some math in two separate lines using "//" as the new line. But this is not working and the elements are rendering on the same line. For example: 

        <MathJaxContext>
            <MathJax>{" a // b "}</MathJax>
        </MathJaxContext>

This renders: 
ab
instead of:
a
b

The same happens when I replace "//" with "////". 

How do I get a new line?

**Comment by fast-reflexes** [comment]
Hi there!

Looks like that line break is only working with MathJax 2 and not in MathJax 3 (https://github.com/mathjax/MathJax/issues/2312). So use `version={2}` in your `MathJaxContext` and it should work. I also suggest you use delimiters in your MathJax code since even if line breaks WOULD work, it wouldn't work if you didn't delimit your MathJax content with appropriate delimiters, much like how it is done in pure MathJax. Please check [example](https://github.com/fast-reflexes/better-react-mathjax#examples).
