### ISSUE TITLE
Error: Typesetting failed: Cannot read properties of null (reading 'contains')

### ISSUE THREAD

**Issue by whlshy** [fast-reflexes/better-react-mathjax#59]
What wrong about this?

![image](https://github.com/fast-reflexes/better-react-mathjax/assets/49122960/a9548fe5-a69e-449d-b977-0e5118470b42)
![image](https://github.com/fast-reflexes/better-react-mathjax/assets/49122960/6f0b3ff3-fa48-4dde-9f6f-6e7a9d94a2f3)

This result appears when I use @tanstack/react-query.

![image](https://github.com/fast-reflexes/better-react-mathjax/assets/49122960/53abafb3-4594-4ba5-b4c0-158782bc672a)

If I comment this line it doesn't happen.

**Comment by whlshy** [comment]
Oh, maybe should have to wait MathJaxContext loaded

**Comment by fast-reflexes** [comment]
I really need more context to understand why this happens :) As long as you have a `MathjaxContext` it should be enough ... dod this happen when you start the project locally? If so, if you give me access, I can have a look.

**Comment by whlshy** [comment]
https://codepen.io/whlshy/pen/JjVmNQz?editors=0011#

![image](https://github.com/fast-reflexes/better-react-mathjax/assets/49122960/b0ad7e98-bade-4696-bc8c-c51236d4f065)

**Comment by fast-reflexes** [comment]
I can't trigger that error ... When I go to that URL and click  `refetch`, it works out fine and I get no errors in the console.

Few tips:
* Wrap you ENTIRE APP in a `MathJaxContext` not just that single component
* Since you're working together with some markdown tool, you really need to be on top of things. Remember MathJax does its work in the DOM after rendering and depending on what the markdown tool does (in terms om manipulation, escaping etc...) you might have to take some extra measures. Every markdown library has its ways so it's most probably doable but might require some extra fiddling (but you already have it working so, obviously no problem, just saying that markdown components and Mathjax are not always best friends).
* You shouldn't have to worry about Mathjax downloading, the library takes care of that and it should not result in any errors even if you render before Mathjax is downloaded.

Let me know what exactly is the problem here because I can't replicate and everything seems to be working fine :D

**Comment by fast-reflexes** [comment]
I will close this in a few days if you can't elaborate on what is wrong so that I can troubleshoot it :)

**Comment by fast-reflexes** [comment]
Can't troubleshoot this since information lacks. Feel free to reopen with more info.
