### ISSUE TITLE
Content is not fully visible in Safari and iPad

### ISSUE THREAD

**Issue by fansari21** [fast-reflexes/better-react-mathjax#67]
At the moment when the content is being loaded, it does not appear in its entirety, and this issue is specifically observed in the Safari browser and on iPad devices. Even after refreshing the page, the content remains partially hidden, as demonstrated in the screenshot provided below.

![image](https://github.com/user-attachments/assets/77e8cf11-27b8-4c39-9a14-03590f61e3ac)

**Comment by fast-reflexes** [comment]
Hello!

I have had no such problems in Safari or on iPads and I suspect it's due to your CSS being interpreted differently in Safari / iPads than in some other contexts. But I will of course check it out if you can provide a sandbox or some kind of reproducible sample which I can inspect. I have used this library in Safari and it renders fine so I need more than just that picture I'm afraid :(

**Comment by fast-reflexes** [comment]
Closing since no response.

**Comment by fansari21** [comment]
I just wanted to inform you that I've created the sandbox, I've tested it across multiple browsers and versions, but I haven't been able to reproduce the issue in the sandbox. I'm continuing to investigate on my end, and I'll update you if I can find a reproducible case.
