### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by peakthink** [fast-reflexes/better-react-mathjax#7]
I used your this package in my react native application, but after configuring it, I'm getting the error saying
Error: Text strings must be rendered within a <Text> component

I'm not able to understand what's the issue is.

**Comment by fast-reflexes** [comment]
I'm not sure if it works with React Native unfortunately. You can try to create a code sandbox with the same code and see if it throws the same error, in that case I can help you but as I said, I have never tested it with React Native :(

**Comment by fast-reflexes** [comment]
Late follow-up, in React Native every string in the app needs to be wrapped in a `Text` block. It's not like in regular React where you can add text a little bit everywhere. 

This error is thus not specifically connected to using Mathjax in React, however, I'm pretty sure this library doesn't work in React Native because this library depends on Mathjax  and Mathjax typesets the DOM and the DOM doesn't exist in React Native (at least not in any mobile apps coming out of it), so I think you will have limited luck with this, but do tell if you're successful :) That specific error that you posted about is however NOT an error indicating the above but only an error indicating that you have loose text somewhere.
